"""Add BaseModel and upgrade AuditLog

Revision ID: 677271f09b99
Revises: fb906728cbca
Create Date: 2026-07-30 14:56:26.842606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '677271f09b99'
down_revision: Union[str, Sequence[str], None] = 'fb906728cbca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('audit_logs', sa.Column('actor', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('entity', sa.String(), server_default='Unknown', nullable=False))
    op.add_column('audit_logs', sa.Column('entity_id', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('old_value', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('new_value', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('ip', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('success', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('audit_logs', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity'), 'audit_logs', ['entity'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.drop_constraint(op.f('audit_logs_organization_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'user_id')
    op.drop_column('audit_logs', 'resource_id')
    op.drop_column('audit_logs', 'ip_address')
    op.drop_column('audit_logs', 'details')
    op.drop_column('audit_logs', 'resource_type')
    op.drop_column('audit_logs', 'created_at')
    op.add_column('organizations', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('organizations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organizations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('organizations', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('products', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('products', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('products', 'updated_by')
    op.drop_column('products', 'created_by')
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('organizations', 'updated_by')
    op.drop_column('organizations', 'created_by')
    op.drop_column('organizations', 'updated_at')
    op.drop_column('organizations', 'deleted_at')
    op.drop_column('organizations', 'is_deleted')
    op.add_column('audit_logs', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('resource_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('resource_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('audit_logs_organization_id_fkey'), 'audit_logs', 'organizations', ['organization_id'], ['id'])
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.drop_column('audit_logs', 'duration_ms')
    op.drop_column('audit_logs', 'success')
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'ip')
    op.drop_column('audit_logs', 'metadata_json')
    op.drop_column('audit_logs', 'new_value')
    op.drop_column('audit_logs', 'old_value')
    op.drop_column('audit_logs', 'entity_id')
    op.drop_column('audit_logs', 'entity')
    op.drop_column('audit_logs', 'actor')
    op.drop_column('audit_logs', 'timestamp')
    # ### end Alembic commands ###
