"""phase_3_4_offline_licenses

Revision ID: 6add7104c7c0
Revises: a08d91a4a58e
Create Date: 2026-07-31 18:36:56.531740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6add7104c7c0'
down_revision: Union[str, Sequence[str], None] = 'a08d91a4a58e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activation_requests', sa.Column('hardware_tokens', sa.JSON(), nullable=True))
    op.alter_column('licenses', 'subscription_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('licenses', 'deployment_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('licenses', 'product_plan_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('licenses', 'product_plan_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('licenses', 'deployment_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('licenses', 'subscription_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('activation_requests', 'hardware_tokens')
    # ### end Alembic commands ###
