"""Release Management and Release Artifacts

Revision ID: 7ed5c634960d
Revises: 533a34b0a28e
Create Date: 2026-07-31 15:53:47.152702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed5c634960d'
down_revision: Union[str, Sequence[str], None] = '533a34b0a28e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_artifacts',
    sa.Column('release_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('architecture', sa.String(), nullable=False),
    sa.Column('artifact_type', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('download_path', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('filesize', sa.Integer(), nullable=False),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('signature_algorithm', sa.String(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('release_id', 'platform', 'architecture', 'artifact_type', name='uq_release_artifact')
    )
    op.create_index(op.f('ix_release_artifacts_id'), 'release_artifacts', ['id'], unique=False)
    op.create_index(op.f('ix_release_artifacts_release_id'), 'release_artifacts', ['release_id'], unique=False)
    op.create_index(op.f('ix_release_artifacts_sha256'), 'release_artifacts', ['sha256'], unique=False)
    op.add_column('releases', sa.Column('build_number', sa.Integer(), nullable=False))
    op.add_column('releases', sa.Column('status', sa.String(), nullable=False))
    op.add_column('releases', sa.Column('minimum_license_build', sa.Integer(), nullable=True))
    op.add_column('releases', sa.Column('minimum_lms_build', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_releases_sha256'), table_name='releases')
    op.drop_constraint(op.f('uq_release_version_platform_arch'), 'releases', type_='unique')
    op.create_unique_constraint('uq_release_version_build', 'releases', ['product_id', 'version', 'build_number'])
    op.drop_column('releases', 'platform')
    op.drop_column('releases', 'filesize')
    op.drop_column('releases', 'download_path')
    op.drop_column('releases', 'sha256')
    op.drop_column('releases', 'installer_type')
    op.drop_column('releases', 'filename')
    op.drop_column('releases', 'minimum_license_plan')
    op.drop_column('releases', 'architecture')
    op.drop_column('releases', 'version_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('version_code', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('releases', sa.Column('architecture', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('releases', sa.Column('minimum_license_plan', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('releases', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('releases', sa.Column('installer_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('releases', sa.Column('sha256', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('releases', sa.Column('download_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('releases', sa.Column('filesize', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('releases', sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_release_version_build', 'releases', type_='unique')
    op.create_unique_constraint(op.f('uq_release_version_platform_arch'), 'releases', ['product_id', 'version', 'platform', 'architecture'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_releases_sha256'), 'releases', ['sha256'], unique=False)
    op.drop_column('releases', 'minimum_lms_build')
    op.drop_column('releases', 'minimum_license_build')
    op.drop_column('releases', 'status')
    op.drop_column('releases', 'build_number')
    op.drop_index(op.f('ix_release_artifacts_sha256'), table_name='release_artifacts')
    op.drop_index(op.f('ix_release_artifacts_release_id'), table_name='release_artifacts')
    op.drop_index(op.f('ix_release_artifacts_id'), table_name='release_artifacts')
    op.drop_table('release_artifacts')
    # ### end Alembic commands ###
