"""add_product_plans

Revision ID: 9bacccde56b4
Revises: d249dfaa6bf3
Create Date: 2026-07-30 16:36:37.892684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9bacccde56b4'
down_revision: Union[str, Sequence[str], None] = 'd249dfaa6bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_plans',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tier', sa.Enum('COMMUNITY', 'PROFESSIONAL', 'ENTERPRISE', 'GOVERNMENT', name='plantier'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DEPRECATED', name='planstatus'), nullable=False),
    sa.Column('max_devices', sa.Integer(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('trial_days', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_plans_id'), 'product_plans', ['id'], unique=False)
    op.create_index(op.f('ix_product_plans_product_id'), 'product_plans', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_plans_slug'), 'product_plans', ['slug'], unique=True)
    op.create_table('product_plan_capabilities',
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('capability_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['product_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'capability_id', name='uq_plan_capability')
    )
    op.create_index(op.f('ix_product_plan_capabilities_capability_id'), 'product_plan_capabilities', ['capability_id'], unique=False)
    op.create_index(op.f('ix_product_plan_capabilities_id'), 'product_plan_capabilities', ['id'], unique=False)
    op.create_index(op.f('ix_product_plan_capabilities_plan_id'), 'product_plan_capabilities', ['plan_id'], unique=False)
    op.drop_index(op.f('ix_dummy_models_id'), table_name='dummy_models')
    op.drop_table('dummy_models')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummy_models',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('dummy_models_pkey'))
    )
    op.create_index(op.f('ix_dummy_models_id'), 'dummy_models', ['id'], unique=False)
    op.drop_index(op.f('ix_product_plan_capabilities_plan_id'), table_name='product_plan_capabilities')
    op.drop_index(op.f('ix_product_plan_capabilities_id'), table_name='product_plan_capabilities')
    op.drop_index(op.f('ix_product_plan_capabilities_capability_id'), table_name='product_plan_capabilities')
    op.drop_table('product_plan_capabilities')
    op.drop_index(op.f('ix_product_plans_slug'), table_name='product_plans')
    op.drop_index(op.f('ix_product_plans_product_id'), table_name='product_plans')
    op.drop_index(op.f('ix_product_plans_id'), table_name='product_plans')
    op.drop_table('product_plans')
    # ### end Alembic commands ###
