"""Add ActivationRequest models

Revision ID: a08d91a4a58e
Revises: fbfe07165e7e
Create Date: 2026-07-31 17:18:20.808718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08d91a4a58e'
down_revision: Union[str, Sequence[str], None] = 'fbfe07165e7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('license_artifacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('license_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_license_artifacts_id'), 'license_artifacts', ['id'], unique=False)
    op.create_index(op.f('ix_license_artifacts_license_id'), 'license_artifacts', ['license_id'], unique=False)
    op.create_table('activation_requests',
    sa.Column('request_number', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('architecture', sa.String(), nullable=True),
    sa.Column('cpu', sa.String(), nullable=True),
    sa.Column('ram', sa.String(), nullable=True),
    sa.Column('bios', sa.String(), nullable=True),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('windows_sid', sa.String(), nullable=True),
    sa.Column('current_build', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('locale', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('reject_reason', sa.String(), nullable=True),
    sa.Column('admin_notes', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by', sa.String(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_license_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generated_license_id'], ['licenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activation_requests_device_id'), 'activation_requests', ['device_id'], unique=False)
    op.create_index(op.f('ix_activation_requests_id'), 'activation_requests', ['id'], unique=False)
    op.create_index(op.f('ix_activation_requests_request_number'), 'activation_requests', ['request_number'], unique=True)
    op.create_table('activation_request_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('status_from', sa.String(), nullable=True),
    sa.Column('status_to', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['activation_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activation_request_events_id'), 'activation_request_events', ['id'], unique=False)
    op.create_index(op.f('ix_activation_request_events_request_id'), 'activation_request_events', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activation_request_events_request_id'), table_name='activation_request_events')
    op.drop_index(op.f('ix_activation_request_events_id'), table_name='activation_request_events')
    op.drop_table('activation_request_events')
    op.drop_index(op.f('ix_activation_requests_request_number'), table_name='activation_requests')
    op.drop_index(op.f('ix_activation_requests_id'), table_name='activation_requests')
    op.drop_index(op.f('ix_activation_requests_device_id'), table_name='activation_requests')
    op.drop_table('activation_requests')
    op.drop_index(op.f('ix_license_artifacts_license_id'), table_name='license_artifacts')
    op.drop_index(op.f('ix_license_artifacts_id'), table_name='license_artifacts')
    op.drop_table('license_artifacts')
    # ### end Alembic commands ###
