"""add_capabilities

Revision ID: d249dfaa6bf3
Revises: 2e5f8f30e2c8
Create Date: 2026-07-30 15:49:47.140216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd249dfaa6bf3'
down_revision: Union[str, Sequence[str], None] = '2e5f8f30e2c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capabilities',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capabilities_id'), 'capabilities', ['id'], unique=False)
    op.create_index(op.f('ix_capabilities_slug'), 'capabilities', ['slug'], unique=True)
    op.create_table('product_capabilities',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('capability_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'capability_id', name='uq_product_capability')
    )
    op.create_index(op.f('ix_product_capabilities_capability_id'), 'product_capabilities', ['capability_id'], unique=False)
    op.create_index(op.f('ix_product_capabilities_id'), 'product_capabilities', ['id'], unique=False)
    op.create_index(op.f('ix_product_capabilities_product_id'), 'product_capabilities', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_capabilities_product_id'), table_name='product_capabilities')
    op.drop_index(op.f('ix_product_capabilities_id'), table_name='product_capabilities')
    op.drop_index(op.f('ix_product_capabilities_capability_id'), table_name='product_capabilities')
    op.drop_table('product_capabilities')
    op.drop_index(op.f('ix_capabilities_slug'), table_name='capabilities')
    op.drop_index(op.f('ix_capabilities_id'), table_name='capabilities')
    op.drop_table('capabilities')
    # ### end Alembic commands ###
