"""add_licenses

Revision ID: fb131786e870
Revises: 89775bb83780
Create Date: 2026-07-30 17:11:34.288322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb131786e870'
down_revision: Union[str, Sequence[str], None] = '89775bb83780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licenses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subscription_id', sa.String(), nullable=False),
    sa.Column('deployment_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('product_plan_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', 'EXPIRED', name='licensestatus'), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_plan_id'], ['product_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licenses_deployment_id'), 'licenses', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_licenses_id'), 'licenses', ['id'], unique=False)
    op.create_index(op.f('ix_licenses_organization_id'), 'licenses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_licenses_product_id'), 'licenses', ['product_id'], unique=False)
    op.create_index(op.f('ix_licenses_product_plan_id'), 'licenses', ['product_plan_id'], unique=False)
    op.create_index(op.f('ix_licenses_subscription_id'), 'licenses', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_licenses_subscription_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_product_plan_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_product_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_organization_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_deployment_id'), table_name='licenses')
    op.drop_table('licenses')
    # ### end Alembic commands ###
