"""Add devices

Revision ID: fbfe07165e7e
Revises: 7ed5c634960d
Create Date: 2026-07-31 16:15:10.754679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbfe07165e7e'
down_revision: Union[str, Sequence[str], None] = '7ed5c634960d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('machine_guid', sa.String(), nullable=True),
    sa.Column('public_key', sa.String(), nullable=True),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('architecture', sa.String(), nullable=True),
    sa.Column('cpu', sa.String(), nullable=True),
    sa.Column('ram', sa.String(), nullable=True),
    sa.Column('bios', sa.String(), nullable=True),
    sa.Column('is_virtual_machine', sa.Boolean(), nullable=True),
    sa.Column('last_ip', sa.String(), nullable=True),
    sa.Column('last_country', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('locale', sa.String(), nullable=True),
    sa.Column('install_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_boot', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uptime', sa.Integer(), nullable=True),
    sa.Column('current_build', sa.Integer(), nullable=True),
    sa.Column('current_version', sa.String(), nullable=True),
    sa.Column('current_channel', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trial_started', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_ends', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('active_license_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['active_license_id'], ['licenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_fingerprint'), 'devices', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_organization_id'), 'devices', ['organization_id'], unique=False)
    op.add_column('licenses', sa.Column('device_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_licenses_device_id'), 'licenses', ['device_id'], unique=False)
    op.create_foreign_key(None, 'licenses', 'devices', ['device_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'licenses', type_='foreignkey')
    op.drop_index(op.f('ix_licenses_device_id'), table_name='licenses')
    op.drop_column('licenses', 'device_id')
    op.drop_index(op.f('ix_devices_organization_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_fingerprint'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
